### PR TITLE
IBM Baremetal Softlayer Machine

### PR DESCRIPTION
**Pull request by jjasghar**
Here is a VM on the IBM cloud with softlayer

Signed-off-by: JJ Asghar <jja@ibm.com>

### CODE REVIEW

**Comment by tas50** [comment]
This doesn't look like a virtualized system @jjasghar. Is this just a softlayer managed supermicro?

**Comment by jjasghar** [comment]
:-O it's supposed to be....

**Comment by tas50** [comment]
Pretty sure you just got a whole box there.

**Comment by jjasghar** [comment]
heh, opps, it is, i put ssh'd into the wrong box :P

**Comment by tas50** [comment]
This is actually super useful for softlayer detection though.

**Comment by jjasghar** [comment]
fixing the PR, one sec.

**Comment by tas50** [comment]
From this PR comes this PR https://github.com/chef/ohai/pull/1318

**Pull request merged**
